// ---------------------------------------------------------------------------
// ROADMAP PROGRESS DATA  (edit this file to update the public roadmap)
// ---------------------------------------------------------------------------
// This is the only file you edit to reflect your progress. Visitors get a
// read-only view; whatever is here is what they see.
//
// Keys are the stage numbers (as strings) from roadmap-stages.js, in reading
// order: "1" is "Build a tokenizer", "2" is "Learn embeddings", and so on.
//
// Entry shape:
//   "1": {
//     done: true,                       // true = completed (green block)
//     sources: [                        // shown in the hover popup when done
//       { label: "Karpathy — Let's build the GPT Tokenizer", url: "https://youtu.be/zduSFxRajkE" }
//     ]
//   },
//   "5": { done: false, note: "Reading the FlashAttention paper" },  // in progress
//
// A stage with no entry is treated as "not started".
// ---------------------------------------------------------------------------

// ROADMAP PROGRESS DATA - generated by x9k-admin-roadmap.html
// Replaces roadmap-data.js. Edit there or regenerate here.

window.ROADMAP_DATA = {
  updated: "2026-09-28",
  stages: {
    "1": { done: true, sources: [,
        { label: "Karpathy — Let's build the GPT Tokenizer", url: "https://www.youtube.com/watch?v=zduSFxRajkE" },
    ] },
    "2": { done: true, sources: [,
        { label: " Thu Vu - Text Embeddings", url: "https://youtu.be/Q6TBHDgWCDQ?si=79ce65znE5pbphBZ" },
    ] },
    "3": { done: false, note: "In progress" }
  }
};
